name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      # todo 增加Nodejs pnpm build 问题
      # 否则 会构建出现找不到dist文件夹的问题
      - name: Build
        run: go build -v ./...

      - name: Make
        run: make build-all



