name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # todo 增加Nodejs pnpm build 问题
      # 否则 会构建出现找不到dist文件夹的问题
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: cd ui && pnpm install
      - name: Build
        run: cd ui && pnpm build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
      - name: Build
        run: go build -v ./...

      - name: Make
        run: make build-all
